name: Bug report
description: Report a reproducible problem in RedTrack
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough details to reproduce the problem.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: App version, OS, browser/device, backend version.
    validations:
      required: true
